name: leafy_notes_database

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: 2.0.3
  flutter:
    sdk: flutter

  lint: ^1.5.3
  moor_flutter: ^4.0.0
  sqlite3_flutter_libs: 0.5.1
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.4
  get: ^4.3.8
  moor_generator: ^4.6.0+1