name: Move Maintenance issues to Maintenance project

on:
  issues:
    types:
      - labeled

jobs:
  add_to_project:
    if: github.event.label.name == 'maintenance'
    runs-on: ubuntu-latest
    steps:
      - uses: skeet70/default-project-board-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: Maintenance
