name: Leafy CI 🌱

on:
  push:
    branches: [ develop ]

  pull_request:
  
  workflow_dispatch:

jobs:
  Build_and_Upload_APK:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter and build 🌱
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
      # - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk --release --build-number "${{ github.run_number }}"
      - run: |
          ls
          cd build
          ls
          cd app
          ls
          cd outputs
          ls
          cd flutter-apk
          ls
    
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: release-apk-${{ github.run_number }}
          path: build/app/outputs/apk/release/app-release.apk

