name: Leafy Launcher CI 🌱

on:
  push:
    branches: [ develop ]

  pull_request:
  
  workflow_dispatch:

jobs:
  LeafyCI:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk --release
    
      - uses: actions/upload-artifact@v1
        with:
          name: leafy-release
          path: build/app/outputs/apk/release/app-release.apk
